
    <!-- jQuery Library -->
   <!-- jQuery Library -->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/jquery-1.11.2.min.js"?>"></script>    
    <!--materialize js-->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/materialize.js"?>"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"?>"></script>  
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins.js"?>"></script>
    </body>
    </html>