
    <!-- jQuery Library -->
   <!-- jQuery Library -->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/jquery-1.11.2.min.js"?>"></script>    
    <!--materialize js-->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/materialize.js"?>"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"?>"></script>
    

    <!-- chartist -->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/chartist-js/chartist.min.js"?>"></script>   

    <!-- chartjs -->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/chartjs/chart.min.js"?>"></script>
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/chartjs/chart-script.js"?>"></script>

    <!-- sparkline -->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/sparkline/jquery.sparkline.min.js"?>"></script>
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/sparkline/sparkline-script.js"?>"></script>

    <!--jvectormap-->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"?>"></script>
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"?>"></script>
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins/jvectormap/vectormap-script.js"?>"></script>    

    
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="<?php echo $G->config["w_url"]. DS . "app" . DS . "media" . DS . "materialize" . DS . "js/plugins.js"?>"></script>
    </body>
    </html>