<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
        <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
        <title><?php echo $G->config["w_nombre"] ?> - <?php echo $G->title ?></title>

        <!-- Favicons-->
        <link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
        <!-- Favicons-->
        <link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
        <!-- For iPhone -->
        <meta name="msapplication-TileColor" content="#00bcd4">
        <meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
        <!-- For Windows Phone -->
        <!-- MATERIALIZE-->
        <!-- CORE CSS-->    
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "materialize" . DS . "css" . DS . "materialize.css" ?>" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "materialize" . DS . "css" . DS . "style.css" ?>"  type="text/css" rel="stylesheet" media="screen,projection">
        <!-- Custome CSS-->    
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "materialize" . DS . "css" . DS . "custom-style.css" ?>"  type="text/css" rel="stylesheet" media="screen,projection">
        <!-- Custome CSS-->    
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "materialize" . DS . "css" . DS . "custom-style.css" ?>"  type="text/css" rel="stylesheet" media="screen,projection">


        <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "materialize" . DS . "js" . DS . "plugins" . DS . "perfect-scrollbar" . DS . "perfect-scrollbar.css" ?>"  type="text/css" rel="stylesheet" media="screen,projection">
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "materialize" . DS . "js" . DS . "plugins" . DS . "jvectormap" . DS . "jquery-jvectormap.css" ?>"  type="text/css" rel="stylesheet" media="screen,projection">
        <link href="<?php echo $G->config["w_url"] . DS . "app" . DS . "media" . DS . "materialize" . DS . "js" . DS . "plugins" . DS . "chartist-js" . DS . "chartist.min.css" ?>"  type="text/css" rel="stylesheet" media="screen,projection">
    </head>
    <body>
        <!-- Start Page Loading -->
        <div id="loader-wrapper">
            <div id="loader"></div>        
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>
        <!-- End Page Loading -->

        <!-- //////////////////////////////////////////////////////////////////////////// -->

        <!-- START HEADER -->
    <!-- START HEADER -->
    <header id="header" class="page-topbar">
        <!-- start header nav-->
        <div class="navbar-fixed">
            <nav class="blue darken-4">
                <div class="nav-wrapper">                    
                    
                    <ul class="left">                      
                        <li><h1 class="logo-wrapper" style="font-size: 25px;"><a href="home" class="brand-logo darken-1" style="font-size: 25px;"><?php echo $G->config["w_nombre"] ?></a> <span class="logo-text">Materialize</span></h1></li>
                    </ul>
                    <ul class="right hide-on-med-and-down">                        
                        <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- end header nav-->
    </header>
    <!-- END HEADER -->