<ul id="slide-out" class="side-nav fixed leftside-navigation">
    <li class="user-details cyan darken-2">
        <div class="row">
            <div class="col col s4 m4 l4">
                <img src="images/avatar.jpg" alt="" class="circle responsive-img valign profile-image">
            </div>
            <div class="col col s8 m8 l8">
                <ul id="profile-dropdown" class="dropdown-content">
                    <li><a href="#"><i class="mdi-action-settings"></i> Config</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $G->config["w_url"] . DS . "logout"; ?>"><i class="mdi-hardware-keyboard-tab"></i> Salir</a>
                    </li>
                </ul>
                <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown"><?php echo $_SESSION['user']; ?><i class="mdi-navigation-arrow-drop-down right"></i></a>
                <p class="user-roal"><?php echo $G->user->data->u_rol; ?></p>
            </div>
        </div>
    </li>
    <li class="bold active"><a href="home" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Inicio</a>
    </li>
    <li class="bold"><a href="#" class="waves-effect waves-cyan"><i class="mdi-editor-insert-invitation"></i> Notas</a>
    </li>
    <li class="li-hover"><div class="divider"></div></li>
    <li><a href="#"><i class="mdi-image-grid-on"></i> Reportes</a>
    </li>                   
</ul>
<a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>